language: node_js
node_js:
  - 12.16.1

services: 
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

install:  
  - echo "Nothing to install"

before_script:
  - docker --version # print the version for logging
  - docker-compose --version # print the version for logging
  # - docker-compose -f docker-compose-build.yaml build --parallel

script: 
  # Build images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverse-proxy ./udagram-reverse-proxy
  # Tag images
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v4a
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v4a
  - docker tag udagram-reverse-proxy $DOCKER_USERNAME/udagram-reverse-proxy:v4a
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:local
  
after_success: 
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to docker hub
  - docker push $DOCKER_USERNAME/udagram-api-feed:v4a
  - docker push $DOCKER_USERNAME/udagram-api-user:v4a
  - docker push $DOCKER_USERNAME/udagram-reverse-proxy:v4a
  - docker push $DOCKER_USERNAME/udagram-frontend:local
  # Fire up the docker-compose file
  - docker-compose up

